### ISSUE TITLE
Update demographic questions and pass on to useR! 2018 organizers

### ISSUE THREAD

**Issue by hturner** [forwards/tasks#1]
We hope to add our demographic questions to the useR! survey again this year. We have previously discussed some revisions required to the questions used last year, I plan to revise the question list and send to useR! 2018 organizers to add to the survey.

**Comment by nujcharee** [comment]
I would like to help!

**Comment by hturner** [comment]
Great, let's work together on this!

**Comment by trallard** [comment]
hey @nujcharee we'll be working on this together 🤩

**Comment by jesse-jesse** [comment]
Hi @nujcharee, @trallard and @hturner, 
I'm helping Di Cook with the UseR survey . Just introducing myself :)

**Comment by hturner** [comment]
Hi Jessie, just sent an invite to the private survey repo.

**Comment by trallard** [comment]
Hi @jesse-jesse 
I will be reviewing some changes that Nujcharee suggested a couple of days ago and then merge them to the main repository. If there is anything you want to discuss/ suggest please do

**Comment by trallard** [comment]
@nujcharee and I had a chat about the questions and have done a revision of the wording/questions asked.

@hturner  I just assigned you as a second reviewer. I think there are only one or two things that need rewording and it should be ok to merge into the Forwards repository.

Also, will we be sending the survey as `.txt` file or as a fully assembled form (Google form, Typeform, SurveyMonkey)

**Comment by hturner** [comment]
Okay I added my review.

I mentioned to @jesse-jesse that the survey platform needs to be considered carefully to ensure it can handle the conditional logic required by the questions and also to ensure sufficient data privacy, in particular meeting GDPR regulations. This probably means using a paid service such as survey monkey which has been used at the past 2 useR!s (paid out of conference budget).

**Comment by jesse-jesse** [comment]
We're planning to use survey monkey for the data collection.

**Comment by hturner** [comment]
Yes, people from under-represented groups tend to have lower SES, so it's definitely related. We touch on this a bit with regards to paid employment status. I think asking questions about income or rurality would not be so relevant/useful for useR! where the participants come from all over the world, since the implications of this depend very much on the local context.

**Comment by jesse-jesse** [comment]
What do you think about adding in drug dependencies or drug abuse question? There is a strong relationships between mental health and drug abuse, however I would say that mental health issues in the lower socio economic circumstances probably translate to a drug abuse label,, while those that can afford to get access to mental health services end up with the mental health label.

**Comment by nujcharee** [comment]
@hturner @trallard Hi there I have committed changes to survey question in https://github.com/forwards/surveys/blob/master/useR2018/demographic_questions.txt 

I revised question 3 - What ethnic group(s) do you identify?
I consulted last year result to finalise the drop down list for the above question. I added a free text for each option should the participants wish to describe / specify their ethnic group.

Also "prefer not to respond" is an option for all questions in the survey.

@trallard - will we add data privacy disclaimer at the end of the survey or this is a separate thing altogether? Thank you :)

**Comment by hturner** [comment]
Thanks @nujcharee, I made a couple of minor changes (added "prefer not to respond" option also to Q1 and Q2, removed Black British as specific case) and moved to the public surveys repo:  https://github.com/forwards/surveys-public/tree/master/survey-forms/useR2018

I think we'll draw a line here, but I will ask @julierennes and @TanjaKec to do a final check as far as the questions go. 

I've separated out the statements on privacy/confidentiality because we still need to do a bit of work on those parts. But @jesse-jesse can you start on adding the current version (demographic_questions.txt) to Survey Monkey? Then we can add the statements/any final changes later. Thanks!

**Comment by jesse-jesse** [comment]
I'll start building the survey.

**Comment by jesse-jesse** [comment]
Would it be fine to have age categories instead of birth year? I don't think I can have a drop down menu with that many options in the survey tool I'm using.

**Comment by jesse-jesse** [comment]
I also added Aboriginal and/or Torres Strait Islander to the ethnic groups. Is this fine?

**Comment by hturner** [comment]
We've used the same age question in the last two surveys done in survey monkey, so it should be possible, if a little tedious. Ideally we would keep the question the same as we then get a smoother estimate of age distribution and more flexibility on specifying age brackets that preserve anonymity. An alternative might be to ask for birth year in a free text box.

For the ethnic groups: good idea about adding Aboriginal and/or Torres Strait Islander, I meant to ask if there were any adjustments we should make to the categories given the conference is in Australia.

**Comment by jesse-jesse** [comment]
Age categories fixed. Didn't take as long as I thought it would. Found a short cut.

**Comment by hturner** [comment]
I've written a draft privacy policy: https://github.com/forwards/surveys-public/blame/master/survey-forms/useR2018/privacy_policy.md.

The idea is to link to it from the introductory comments of the useR! 2018 survey: https://github.com/forwards/surveys-public/blame/master/survey-forms/useR2018/top_matter.txt
however I've tried to write it to cover all our data collection, since we need to tighten up on our policies here.

I've opened up a [discussion for members of the Forwards GitHub organization](https://github.com/orgs/forwards/teams/forwards-taskforce/discussions), but others can comment here, or on specific lines in the relevant commits (click on the link in the left hand side of the blame view to jump to the commit where the line(s) were added).

I've asked for comments by Friday 6th July so we have time to get the policy up before running the survey at useR!

**Comment by julierennes** [comment]
Thank you so much, I am just reading the survey, this is great! if not too late I am wondering if for the question 9, we should add  but this does not include postdocs: Are you currently a student? (Note this includes PhD students, even if 
salaried but this does not include postdocs)
Question 11: because the question said if currently in paid I think we can remove the answer: I am not currently in paid employment
Thank you,
JJ

**Comment by julierennes** [comment]
ok!

**Comment by hturner** [comment]
@jesse-jesse I've now updated the top matter with the link to the new privacy policy. So I think the only jobs left to do are to add/update the top matter to the start of the survey and add the note @julierennes suggested to Q9.

I suggest the survey is emailed to participants around lunchtime on the last day as some people will have to leave early, but this gives a chance for it to be mentioned in the final session. Then it would be great if you could send a reminder about 1 week after, possibly also 2 weeks after dependning on response rate. 

Let us know if any further issues!

**Comment by jesse-jesse** [comment]
perfect! updating first thing tomorrow morning. Thanks everyone :)

**Comment by jesse-jesse** [comment]
Quick question. Am I making all the questions non-compulsory? Or do I make them compulsory but the "Prefer not to answer" options enables it to be optional. ?? they are currently not compulsory but  just thought maybe they should be compulsory?

**Comment by dicook** [comment]
if they have “prefer not to answer” it should be compulsory

> On Jul 10, 2018, at 9:29 AM, Jessie <notifications@github.com> wrote:
> 
> Quick question. Am I making all the questions non-compulsory? Or do I make them compulsory but the "Prefer not to answer" options enables it to be optional. ?? they are currently not compulsory but just thought maybe they should be compulsory?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------
Professor Dianne Cook
Department of Statistics
2415 Snedecor Hall
Iowa State University
Ames IA 50011-1210
1-515-294-8865
http://dicook.github.io/
dicook@iastate.edu
@visnut





~*~*~*~
Professor Dianne Cook
Department of Econometrics and Business Statistics
E762A Menzies Building 
20 Chancellors Walk
Monash University
Clayton, VIC 3800
+61 (0)3 990 52608 (office)
+61 (0)4 312 71613 (mobile)
dicook@monash.edu
http://dicook.github.io
@visnut

**Comment by jesse-jesse** [comment]
Hi all, here's is the survey. Please let me know if you find any typos or errors/ missing notes etc. 
https://visnut.wufoo.com/forms/q1561t2z0e38hc8/

**Comment by jesse-jesse** [comment]
Oh no!!!! Something happened with the age question........ :( it has
flipped back to categories. Damn it. It took me ages to put the individual
ages in... I’m so sorry I didn’t see that something had gone wrong. :(

**Comment by hturner** [comment]
Sorry I didn't get a chance to check the survey before it went out, been a busy week with a lot of travelling. Not to worry about the age question, the results will still be useful. If you have a chance, it would still be helpful to add a "No impairment" option to the impairments question - I guess people are working round this by writing in the "Other" box and this will save some re-coding later!

Thanks for getting this up and running!

**Comment by hturner** [comment]
Since the survey is about to close, I'm closing this issue now - the analysis will be a separate task!
