### ISSUE TITLE
Regularly updating news items and events on homepage of Forwards website

### ISSUE THREAD

**Issue by hturner** [forwards/tasks#10]
Items should be gathered from members of the taskforce. This might be done on the taskforce slack, e.g. via a social-media-news channel, with updates added as they come in, or it might be done by collecting items in the core team/slackathon minutes, or some other way the task owner comes up with.

I can mentor on how to add to the home page if required (can do just via browser on GitHub once you have write permissions).

**Comment by jtr13** [comment]
With some guidance I can do this. Joyce

**Comment by jtr13** [comment]
Ok, great, glad to be able to get more involved.

**Comment by hturner** [comment]
I've written up some instructions here: https://github.com/forwards/social-media/blob/master/update-new-events.md - feel free to edit if you think the instructions can be improved or update as you develop the workflow. This is a public version of what I sent on slack - there I have given a few more specific details regarding current news and events.

**Comment by jtr13** [comment]
I'm on it. I'll add a link to your new instructions in the README. Shall I close this issue?

**Comment by hturner** [comment]
Thanks, yes we can close this now.

**Comment by hturner** [comment]
If it helps @jtr13 we could add a task list here, so you could check off each month?

**Comment by jtr13** [comment]
Yes, that would be fantastic!

**Comment by hturner** [comment]
Okay, let's see how this goes - I think you (or current assignee) can uncheck all at the start of a new year!

- [ ] January
- [ ] February
- [ ] March
- [ ] April
- [ ] May
- [ ] June
- [ ] July
- [ ] August
- [ ] September
- [ ] October
- [ ] November
- [ ] December
