### ISSUE TITLE
Co-ordinating blog posts

### ISSUE THREAD

**Issue by hturner** [forwards/tasks#11]
we need someone to help keep on top of the blog. This would include: 
- co-ordinating blog series such as the "R in ..." series or an interview series and finding people to work on each post (author(s) can be anybody from the R community). Other taskforce members may provide ideas
- co-ordinating with taskforce sub-teams on writing blog posts on their work such as survey results/workshop reports. Usually other taskforce members would write the post, but may need support in publishing them on the website
- editing and publishing other contributed posts

Familiarity with blogdown or a willingness to get familiar with it is necessary. Comfort with editing posts would be a bonus. We already have a backlog of planned blog posts, including:
- A contributed blog post that just needs a bit of editing in order to publish; with a tentative milestone of June (it is about an event in November, so not too much rush).
- "R in Asia" that @tbs08 (and @qinwf?) are working on.
- Blog post on Forwards workshops from the teaching team.

The README on https://github.com/forwards/website_source describes how our website is set up and how to add content. @qinwf set up the build and can provide technical support.

If required, I can mentor someone in publishing the contributed post that is almost ready to get them started as a blog co-ordinator.

**Comment by missaugustina** [comment]
I believe @hturner tapped me for this!

**Comment by hturner** [comment]
The contributed blog post on the HavanaR workshop has now been published. We can keep the issue open for now to represent ongoing work on co-ordinating the blog. Perhaps an issue with tasklist can be added to the website_source repo to keep track of sub-tasks, this can be added to the project board.

**Comment by hturner** [comment]
@lornamariak is going to take on the blog co-ordination, so we'll close this issue now
