### ISSUE TITLE
Create updated summary of CRAN maintainer demographics based on survey data

### ISSUE THREAD

**Issue by hturner** [forwards/tasks#17]
Collaboration with Gustavo Pinto and Igor Wiese, researchers that conducted study of CRAN maintainers (How Do Scientists Develop Scientific Software? [paper](http://gustavopinto.org/lost+found/saner-rene2018.pdf), [blog post](http://gustavopinto.org/blog/how-do-scientists-develop-software/)).

**Comment by maelle** [comment]
Can you name the issue "self-declared demographics" in order to make sure there's no misunderstanding? 😸

**Comment by hturner** [comment]
Since not everyone declares their demographics, clarified it will be based on survey data.

**Comment by annnvv** [comment]
Tracked down the raw survey data from the Pinto et al. paper: https://raw.githubusercontent.com/fronchetti/SANER-2018/master/Survey/actual.csv

**Comment by annnvv** [comment]
Task completed in PR: https://github.com/forwards/website_source/pull/108
