### ISSUE TITLE
Viability of running a satRday in Tanzania in parallel to FOSS4G

### ISSUE THREAD

**Issue by DragonflyStats** [forwards/tasks#34]
FOSS4G - an Open Source GIS conference - is taking place in Dar Es Salaam, Tanzania in September.
It might be too short notice, but we can see about helping and facilitating a satRday event in 
parallel. 

R is quite commonly used in the GIS, so it is plausible that a few volunteers could be recruited
from the attendees to help out, give talks, workshops etc.

A key question is who is involved in the Tanzanian R community who could lead the project?

**Comment by hturner** [comment]
Think this might be a bit short notice unless you can identify some local organizers. It is worth keeping an eye out for such connections though.
