### ISSUE TITLE
Berlin SatRDay

### ISSUE THREAD

**Issue by noatamir** [forwards/tasks#4]
Main Orginiser: Noa Tamir

Current tasks:
- [ ] Looking for co-orginisers
- [ ] Looking for location
- [ ] Finalise date/slot with RUG schedule
- [ ] setup website/twitter

**Comment by DragonflyStats** [comment]
Speculative list of collaborators
1. David Higgins (https://www.linkedin.com/in/daveh19/) - initial contact made by KOB
2. Matti Lyra (https://www.linkedin.com/in/mattilyra/) 
3. Katerine Jarmul (https://twitter.com/kjam)

**Comment by DragonflyStats** [comment]
How do we go about getting a URL like http://cardiff2018.satrdays.org/
We could get one for Washington DC while we are at it.
