### ISSUE TITLE
Blog post(s) about past teaching workshops

### ISSUE THREAD

**Issue by emdodwell** [forwards/tasks#43]
Blog post about teaching workshops that have occurred thus far.  These can be individual (i.e. one post per city) or a combined effort, with a description of and highlights from each.  Discussion on slack in #teaching.

**Comment by lornamariak** [comment]
I have gone through the current progress of the blog post and we need updates on this: 

- Bedminster, NJ 
- Melbourne

after that, I will help do some final touches and we publish it.

**Comment by angela-li** [comment]
Added Chicago February 2019 workshop information - please let me know if you need anything else from me!
