### ISSUE TITLE
Forwards Rmarkdown template

### ISSUE THREAD

**Issue by noatamir** [forwards/tasks#5]
- [ ] create Rmarkdown template with Forwards branding to be used for future Forwards talks and workshops

**Comment by maelle** [comment]
xaringan theme?

**Comment by maelle** [comment]
If xaringan theme check out https://alison.rbind.io/post/r-ladies-slides/

**Comment by hturner** [comment]
can you work in the new forwards/branding repo for this, thanks

**Comment by trallard** [comment]
since there is a Rmarkdown template being created for talks and workshops I was wondering it would be worth also having one for the surveys or any other 'report' we want to create?

**Comment by hturner** [comment]
Not sure it is so important for that - as we create html reports they take on the branding of our website, e.g. https://forwards.github.io/docs/mca_community_user2016_survey/

I guess it would be nice to have a consistent style across the Data page, blog posts and reports in terms of graphics. Most of the time this will be determined by the survey report template, as plots will be taken from that for blog posts/the Data page. But sometimes we create plots based on other people's data, or perhaps new plots that combine results from several surveys. So maybe a ggplot theme is the way to go here.

**Comment by mine-cetinkaya-rundel** [comment]
We now have a xaringan Forwards template, per https://github.com/forwards/fwdbrand/pull/24.
