### ISSUE TITLE
Blog post on R in Africa

### ISSUE THREAD

**Issue by lornamariak** [forwards/tasks#53]
A blog post covering the activities that AfricaR has been doing recently with the new chapters and existing chapters.
I am in contact with https://mobile.twitter.com/Shel_Kariuki to see where the blog post she had been putting together is heading. 
Under this same blog, we can share stories of 
R in Somalia and R in eSwatini. I have been in touch with contacts.

**Comment by lornamariak** [comment]
Draft in progress.
Shel shared her input on the state of Africa R initiative.
In touch with R in Somalia and Eswatini, R ladies in Cotonou: these will be our diversity groups in focus.
Reaching out to Denis on the events and conferences so far.

**Comment by lornamariak** [comment]
In review: https://github.com/forwards/website_source/pull/90
Should be ready to publish soon

**Comment by hturner** [comment]
Now online.
