### ISSUE TITLE
Put scholarship application form on LimeSurvey

### ISSUE THREAD

**Issue by hturner** [forwards/tasks#54]
Convert the workshop scholarship application form to a LimeSurvey survey.

**Comment by 3mmaRand** [comment]
Hello!
I *think* I've done this.
https://rfoundation.limequery.com/admin/survey/sa/view/surveyid/635177
Bit of a newbie to github and totally to lime so apols in advance for any errors/ignorance

**Comment by hturner** [comment]
Great! I'll try to take a look over the next week or so.
