### ISSUE TITLE
Trans*Code Event London

### ISSUE THREAD

**Issue by DragonflyStats** [forwards/tasks#6]
Trans*Code is a hack event series focused solely on drawing attention to transgender issues and opportunities.

Open to trans and non-binary folk, and allies; coders, designers and visionaries of all sorts, Trans*Code is inspired by the groundbreaking Trans*H4CK events created by Dr. Kortney Ziegler. The event that aims to help draw attention to transgender issues through a topic-focused hackday. Community members not currently working in technology are also encouraged to participate.

The next Trans*code event is taking place in London on the 8th June, as part of PyLondinium Conference.

Kevin O'Brien is planning to attend as an Forwards Delegate.

**Comment by trallard** [comment]
I _might_ be able to join too... but still need to sort some things out
