### ISSUE TITLE
Create logo with white background and use as GitHub avatar

### ISSUE THREAD

**Issue by maelle** [forwards/tasks#8]
Based on https://github.com/forwards/website_source/blob/master/static/images/logo.R

Or using `magick`

To prevent

![screenshot_20180526-095543](https://user-images.githubusercontent.com/8360597/40578727-0fc51e3a-60ce-11e8-9be1-6ee44b0746d3.jpg)

**Comment by hturner** [comment]
Thanks for the PR @maelle, this is now the GitHub avatar.

**Comment by maelle** [comment]
Cool thx

**Comment by hturner** [comment]
Sorry, all those commits were me messing about trying to export the logo files (with git history!) from forwards/website_source to a new forwards/branding repo - got there in the end!
