### ISSUE TITLE
Blog Twitter card

### ISSUE THREAD

**Issue by maelle** [forwards/tasks#9]
Make it use logo

Cf https://xvrdm.github.io/2017/10/23/socialize-your-blogdown/ h/t @hturner 

Cf also #8

**Comment by hturner** [comment]
Examples of how twitter cards look currently, 

for blog post:
 https://twitter.com/R_Forwards/status/960544164185346049
for event page (sub-page of edu section): 
https://twitter.com/visnut/status/1043279074636914688
for home page:
https://twitter.com/revodavid/status/858002452485996546

**Comment by hturner** [comment]
I haven't checked - I was collecting these examples so we had a better idea of what needs to be added where. E.g. the blog posts seem to have a good description added automatically, whereas we probably need to add something to the relevant partial to get this set up on static pages. If you're happy to assign yourself to this task, that would be great! (No great time pressure on this one!)

**Comment by maelle** [comment]
I've set a reminder to have a look in two weeks 😺

**Comment by maelle** [comment]
Reg the about etc page you need to add a description in their YAML header e.g. in https://github.com/maelle/website_source/blob/master/content/about.md
https://github.com/maelle/website_source/blob/master/content/edu/_index.md

https://cards-dev.twitter.com/validator is very handy

**Comment by maelle** [comment]
and I'm thinking it might be better to use Opengraph tags rather than Twitter tags since Twitter uses both, and Facebook uses Opengraph maybe? I don't use Facebook at all.

**Comment by hturner** [comment]
@maelle pointed out this Twitter card validator: https://cards-dev.twitter.com/validator and I found there is a similar thing for Facebook: https://developers.facebook.com/tools/debug/sharing/. This showed that Opengraph would be better for Facebook and possibly other places (e.g. Slack, LinkedIn) too.

**Comment by hturner** [comment]
Closed by forwards/website_source@c50ae2c.
